name: Test Workflow

on: workflow_dispatch
#  push:
#    branches: [ "master", "developer" ]
#  pull_request:
#    branches: [ "master", "developer" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: sergiofdf
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
