name: Test Workflow

#on: workflow_dispatch
on:
  push:
    branches: [ "master", "developer" ]
  pull_request:
    branches: [ "master", "developer" ]

jobs:
  create_image:
    name: Executando job de criacao da imagem
    runs-on: ubuntu-latest
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: sergiofdf
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
